# Uncomment this line to define a global platform for your project
 platform :ios, '9.0'

target 'CoreMotionStudy' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CoreMotionStudy
pod 'Masonry', '~> 1.0.2'
  target 'CoreMotionStudyUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
